### ISSUE TITLE
proyecto_01

### ISSUE THREAD

**Issue by jorgeluis098** [unamfi/sistop-2020-1#29]
Hola, ¿Cual es el formato del archivo de la reseña de la revista miComputer? PDF? .txt? word ?

**Comment by gwolf** [comment]
jorgeluis098 dijo [Sun, Aug 25, 2019 at 03:13:49PM -0700]:
> Hola, ¿Cual es el formato del archivo de la reseña de la revista
> miComputer? PDF? .txt? word ?

Si no se los especifiqué, el que más les acomode.

Saludos,
