### ISSUE TITLE
No carga una imagen en readme de Práctica 2

### ISSUE THREAD

**Issue by gandresto** [unamfi/sistop-2020-1#52]
Hola, profesor.

Así me muestra el archivo que está en https://github.com/unamfi/sistop-2020-1/blob/master/practicas/2/README.md

![image](https://user-images.githubusercontent.com/25393032/63994020-ac98d080-cab8-11e9-9868-cf7709553018.png)

P.D. No sé si este sea un buen procediento para marcar errores

**Comment by gwolf** [comment]
Muy buen procedimiento para marcar errores, así queda registrada la historia ☺
Me había faltado subir la imagen, ya quedó.
